[Release] 인벤토리 기능을 구현한다.
woowacourse-teams/2022-f12 pull request #166
Opened 2022-07-19 08:51 UTC by yh20studio

# [FE] 작업 내용

# [BE] 작업 내용

2022-07-19 09:54 UTC, yangdongjue5510 commented on backend/src/main/java/com/woowacourse/f12/domain/InventoryProduct.java
> +    }
생성자가 먼저 와야 될 것 같아요!

2022-07-19 10:15 UTC, yangdongjue5510 commented on backend/src/test/java/com/woowacourse/f12/acceptance/InventoryProductAcceptanceTest.java
> +
```java
        ExtractableResponse<Response> response = GET_요청을_보낸다("/api/v1/login?code=dkasjbdkjas");
        LoginResponse loginResponse = response.as(LoginResponse.class);
        String token = loginResponse.getToken();
        Long memberId = loginResponse.getMember().getId();
```

이렇게 로컬 변수로 해보는 건 어땠을까요??

2022-07-19 10:36 UTC, yangdongjue5510 commented on backend/src/test/java/com/woowacourse/f12/documentation/InventoryDocumentation.java
> +        // then
공백 넣어주면 좋겟네용~

2022-07-19 10:38 UTC, hamcheeseburger requested changes
이번 기능도 수고하셨습니당 :)
조금 수정됐으면 하는 부분과 답변 받고 싶은 내용이 있어 Request Changes할게요!

2022-07-19 10:45 UTC, yangdongjue5510 approved these changes
확인했습니다.

2022-07-19 11:22 UTC, jswith requested changes
인벤토리 기능 고생하셨습니다!
사소한 리뷰 몇가지 남겼습니다~

2022-07-19 11:22 UTC, jswith commented on frontend/src/components/common/ProductSelect/ProductSelect.tsx
> +    otherProducts,
otherProducts는 대표 장비에 추가되지 않은 Products를 의미하는건가요?
`'선택되지 않은' 상품`의 의미를 네이밍에 담는게 어떨까요?

2022-07-19 11:22 UTC, Ohzzi requested changes
수고가 많았습니다 😄 
잘 구현해주시고 테스트도 꼼꼼하네요. 몇 가지 수정할만한 부분이 있어서 일단 RC 날릴게요!

2022-07-19 11:22 UTC, Ohzzi commented on backend/src/main/java/com/woowacourse/f12/application/InventoryProductService.java
> +        }
여기는 메서드 분리 하는게 좋아보입니다!

2022-07-19 11:22 UTC, Ohzzi commented on backend/src/main/java/com/woowacourse/f12/application/InventoryProductService.java
> +    }
`Member`를 직접 쓰는 것이 아니고 `orElseThrow`에 목적이 있다면 `jpaRepository` 내장 메서드인 `existsById`가 더 나을 것 같다는 생각도 드네요

2022-07-19 11:22 UTC, Ohzzi commented on backend/src/main/java/com/woowacourse/f12/dto/response/InventoryProductResponse.java
> +    private boolean selected;
여기서는 `selected`고 도메인에서는 `isSelected`네요 통일이 필요할 것 같아요

2022-07-19 11:22 UTC, Ohzzi commented on backend/src/test/java/com/woowacourse/f12/acceptance/InventoryProductAcceptanceTest.java
> +        ExtractableResponse<Response> saveProfileProductResponse = 로그인된_상태로_GET_요청을_보낸다(
`GET` 요청을 보내는데 `saveProfileProductResponse`라고 하면 어색합니다. 뭔가 저장 요청을 보낸것에 대한 응답 같은 느낌이에요

2022-07-19 11:22 UTC, Ohzzi commented on backend/src/test/java/com/woowacourse/f12/documentation/InventoryDocumentation.java
> +        // then
```suggestion
        // when
        ResultActions resultActions = mockMvc.perform(
                get("/api/v1/members/inventoryProducts")
                        .header(HttpHeaders.AUTHORIZATION, authorizationHeader)
        );
        
        // then
```

2022-07-19 11:22 UTC, Ohzzi commented on backend/src/test/java/com/woowacourse/f12/documentation/InventoryDocumentation.java
> +                .andDo(document("inventoryProducts-get-my"));
사소한거지만 `get-my` 보다는 `get-mine`이 나아보입니다!

2022-07-19 11:22 UTC, Ohzzi commented on backend/src/test/java/com/woowacourse/f12/documentation/InventoryDocumentation.java
> +        );
```suggestion
        ResultActions resultActions = mockMvc.perform(
                get("/api/v1/members/" + memberId + "/inventoryProducts")
        );
```

2022-07-19 11:35 UTC, jswith approved these changes
주소 변경 확인했습니다!

2022-07-19 23:17 UTC, hamcheeseburger approved these changes

2022-07-20 00:45 UTC, Ohzzi approved these changes

2022-07-20 00:45 UTC, Ohzzi commented on backend/src/main/java/com/woowacourse/f12/domain/InventoryProduct.java
> +    }
혹시나 프록시 때문에 `instanceof`를 사용한 거라면 `that.id`로 비교하면 프록시는 동등성 통과 못합니다
일단 `InventoryProduct`가 프록시로 사용될 일은 없으니 approve 할게요!

2022-07-20 00:46 UTC, merged