[Feature/BE] 사용자 별로 작성한 리뷰 조회 기능 구현d
woowacourse-teams/2022-f12 pull request #448
Opened 2022-08-11 11:59 UTC by Youngyoon-1

# 작업 내용
- 사용자가 작성한 리뷰목록 조회 기능 구현
- 사용자가 작성한 리뷰 단건 조회 기능 구현

2022-08-11 16:41 UTC, Ohzzi requested changes
생각해볼만한 부분이 꽤 많은 것 같아서 Approve 대신 RC를 남기도록 하겠습니다! 확인하고 반영할 부분은 반영해주세요 :)

2022-08-11 16:41 UTC, Ohzzi commented on backend/src/main/java/com/woowacourse/f12/application/inventoryproduct/InventoryProductService.java
> +    }
`InventoryProduct`를 사용하여 조회하기는 하지만, 실제로 요청에 대해 원하고자 하는 응답은 `Review`에 관련된 부분이기 때문에(실제로 반환값도 `Review`에 관련된 DTO로 나갑니다.), 이 메서드는 `ReviewService`에 있는 것이 적절할 것 같아요.

2022-08-11 16:41 UTC, Ohzzi commented on backend/src/main/java/com/woowacourse/f12/presentation/inventoryproduct/InventoryProductController.java
> +    }
여기도 마찬가지로 조회 대상이 `Review`라면 `ReviewController`에 들어가 있는 것이 맞을 것 같아요. 다른 컨트롤러들의 URL 매핑을 보면 가장 마지막에 오는 도메인이 조회 대상이고, 조회 대상의 컨트롤러에 메서드가 존재하고 있습니다.

2022-08-11 16:41 UTC, Ohzzi commented on backend/src/main/java/com/woowacourse/f12/dto/response/review/ReviewWithAuthorAndProductResponse.java
> +                review.getCreatedAt().toString());
개행에 기준이 애매한 것 같아요. 일정 길이 이상에 개행이라면 `review.getRating`과 `review.getCreatedAt.toString`이 한 줄에 같이 있어야 하지 않을까요?

2022-08-11 16:41 UTC, Ohzzi commented on backend/src/main/java/com/woowacourse/f12/dto/response/review/ReviewWithAuthorResponse.java
>      }
명확한 네이밍 👍

2022-08-11 16:41 UTC, Ohzzi commented on backend/src/main/java/com/woowacourse/f12/dto/response/review/ReviewWithProductResponse.java
> +                                      final String createdAt) {
여기도 `rating`과 `createdAt`이 같은 줄에 있거나, 아니면 파라미터마다 전부 개행을 하는게 맞을 것 같아요!

2022-08-11 16:41 UTC, Ohzzi commented on backend/src/main/java/com/woowacourse/f12/presentation/inventoryproduct/InventoryProductController.java
>      }
프론트엔드와도 논의가 필요한 부분이겠지만, 이렇게 자기 자신의 `InventoryProduct`를 조회 및 수정하는 경우는 아예 `members`를 빼는 것은 어떻게 생각하는지 궁금합니다.

2022-08-11 16:41 UTC, Ohzzi commented on backend/src/main/java/com/woowacourse/f12/presentation/review/ReviewController.java
> +    public ResponseEntity<ReviewWithProductPageResponse> showPageByMe(@VerifiedMember final Long memberId,
제안) `showMyReviewsPage`는 어떤가요? `ByMe`가 여기에 붙는게 약간 이상한 것 아닌가 하는 생각도 드네요

2022-08-11 16:41 UTC, Ohzzi commented on backend/src/main/java/com/woowacourse/f12/application/review/ReviewService.java
> +                .orElseThrow(MemberNotFoundException::new);
`ReviewRepository`에서 `findByProduct` 대신 `findByProductId`를 만든 것이 불필요한 `select` 대신 `exists` 쿼리로 대체하기로 해서 그런 것으로 기억하는데요, 이 부분을 통일할 필요가 있을 것 같아요. 저는 개인적으로 `member`를 조회의 조건으로만 쓸 거라면 굳이 select 해 올 필요가 없다고 생각합니다.

2022-08-12 01:36 UTC, yangdongjue5510 requested changes
확인했습니다 수정해주세요!

2022-08-12 01:36 UTC, yangdongjue5510 commented on backend/src/main/java/com/woowacourse/f12/dto/response/review/ReviewWithProductResponse.java
> +        return new ReviewWithProductResponse(review.getId(), ProductResponse.from(review.getProduct()),
인자를 원칙을 정해서 개행하면 어떨까요?
어떤 줄은 2개 인자를 주고, 어떤 줄은 인자 1개를 주도록 작성하는 게 어색해서요

2022-08-12 01:36 UTC, yangdongjue5510 commented on backend/src/test/java/com/woowacourse/f12/acceptance/ReviewAcceptanceTest.java
> +                () -> assertThat(response.as(ReviewWithProductPageResponse.class).isHasNext()).isFalse(),
`response.as(ReviewWithProductPageResponse.class)` 를 필드로 안뺀 이유가 있나요?

2022-08-12 01:36 UTC, yangdongjue5510 commented on backend/src/test/java/com/woowacourse/f12/acceptance/ReviewAcceptanceTest.java
> +                        .extracting("id")
여기도 필드로 빼서 사용해보는 건 어떨까요

2022-08-12 01:36 UTC, yangdongjue5510 commented on backend/src/test/java/com/woowacourse/f12/application/review/ReviewServiceTest.java
> +                () -> verify(memberRepository).findById(any(Long.class)),
개행이 조금 어색하게 된 것 같네요
`assertThatThrownBy(....)
.isINstanceOf(....)`
이런 식으로 하면 어떨까요

2022-08-12 01:44 UTC, yh20studio requested changes
고생하셨습니다!
반복되는 부분이 많아서 리뷰가 많아졌네요 ㅠㅜ.. 화이팅!

2022-08-12 01:44 UTC, yh20studio commented on backend/src/main/java/com/woowacourse/f12/dto/response/review/ReviewWithAuthorPageResponse.java
> +}
매개변수에 final 붙여주세요!

2022-08-12 01:44 UTC, yh20studio commented on backend/src/main/java/com/woowacourse/f12/dto/response/review/ReviewWithProductResponse.java
> +                                      final String createdAt) {
dto가 명확하게 분리가 되었네요 👍

2022-08-12 01:44 UTC, yh20studio commented on backend/src/main/java/com/woowacourse/f12/dto/response/review/ReviewWithAuthorAndProductResponse.java
> +                review.getCreatedAt().toString());
개행 기준을 잘 정해주세요!

2022-08-12 01:44 UTC, yh20studio commented on backend/src/main/java/com/woowacourse/f12/dto/response/review/ReviewWithProductResponse.java
>  }
여기도 dto new로 만들 때 매개변수 개행 기준이 통일되면 좋겠네요

2022-08-12 01:44 UTC, yh20studio commented on backend/src/main/java/com/woowacourse/f12/presentation/inventoryproduct/InventoryProductController.java
> +    }
리뷰를 보여주는 것이니까 리뷰컨트롤러가 더 어울려 보입니다

2022-08-12 01:44 UTC, yh20studio commented on backend/src/test/java/com/woowacourse/f12/acceptance/InventoryProductAcceptanceTest.java
> +    }
윗줄에 product 객체와 review 객체가 존재하니 id 값을 꺼내서 검증하기 보다는
dto가 분리되고 복잡해진만큼 구조적으로 어떤것이 나가는지 확인할 수 있으면 좋을 거 같아요

2022-08-12 01:44 UTC, yh20studio commented on backend/src/test/java/com/woowacourse/f12/acceptance/ReviewAcceptanceTest.java
> +        Long reviewId2 = Location_헤더에서_id값을_꺼낸다(REVIEW_RATING_4.작성_요청을_보낸다(product2.getId(), token));
파일 체인지가 없어서  여기에 남깁니다만...
이 ReviewAcceptanceTest 에 있는 리뷰를 작성하고 해당 id 값을 가져오는 메서드에서 
Long 타입이 아닌 long 타입을 사용하는 곳이 있습니다.
해당 코드들 Long으로 바꿔주시면 좋을 거 같아요

2022-08-12 01:44 UTC, yh20studio commented on backend/src/test/java/com/woowacourse/f12/acceptance/ReviewAcceptanceTest.java
> +    }
여기도 dto 이름과 같이 review와 product가 함께 있는 구조이다보니
리뷰 id만 추출해서 검증하기 보다는 product도 함께 검증할 수 있으면 좋겠습니다

2022-08-12 01:44 UTC, yh20studio commented on backend/src/test/java/com/woowacourse/f12/acceptance/ReviewAcceptanceTest.java
> +    }
여기도 dto 이름과 같이 review와 product가 함께 있는 구조이다보니
리뷰 id만 추출해서 검증하기 보다는 product도 함께 검증할 수 있으면 좋겠습니다 22

2022-08-12 01:44 UTC, yh20studio commented on backend/src/test/java/com/woowacourse/f12/application/inventoryproduct/InventoryProductServiceTest.java
> +        );
`() -> verify(inventoryProductRepository).findById(eq(1L)),`
eq 빠져도 될거 같아요!

2022-08-12 01:44 UTC, yh20studio commented on backend/src/test/java/com/woowacourse/f12/application/inventoryproduct/InventoryProductServiceTest.java
> +    }
() -> verify(inventoryProductRepository).findById(eq(1L)),
eq 빠져도 될거 같아요! 22

2022-08-12 01:44 UTC, yh20studio commented on backend/src/test/java/com/woowacourse/f12/application/inventoryproduct/InventoryProductServiceTest.java
> +        );
() -> verify(inventoryProductRepository).findById(eq(1L)),
eq 빠져도 될거 같아요! 33

2022-08-12 01:44 UTC, yh20studio commented on backend/src/test/java/com/woowacourse/f12/application/review/ReviewServiceTest.java
> +    }
() -> verify(memberRepository).findById(eq(1L)),
eq 빠져도 될거 같아요! 44

2022-08-12 01:44 UTC, yh20studio commented on backend/src/test/java/com/woowacourse/f12/application/review/ReviewServiceTest.java
> +
final 들어갔네요!

2022-08-12 01:44 UTC, yh20studio commented on backend/src/test/java/com/woowacourse/f12/application/review/ReviewServiceTest.java
> +    }
` () -> verify(memberRepository).findById(any(Long.class)),`
확실히 1L이 들어가는 것을 확인할 수 있으니
` () -> verify(memberRepository).findById(1L),`
은 어떨까요?

2022-08-12 01:44 UTC, yh20studio commented on backend/src/test/java/com/woowacourse/f12/documentation/review/ReviewDocumentation.java
> +                get("/api/v1/members/" + memberId + "/reviews?size=2&page=0&sort=createdAt,desc"));
final 빼주세요!

2022-08-12 01:44 UTC, yh20studio commented on backend/src/test/java/com/woowacourse/f12/documentation/review/ReviewDocumentation.java
> +
final 빼주세요!

2022-08-12 01:44 UTC, yh20studio commented on backend/src/test/java/com/woowacourse/f12/presentation/inventoryproduct/InventoryProductControllerTest.java
> +    }
eq 빠져도 됩니다!

2022-08-12 02:32 UTC, Youngyoon-1 commented on backend/src/test/java/com/woowacourse/f12/acceptance/ReviewAcceptanceTest.java
> +    }
실제 예상 객체를 만들어서 테스트하려면 제품의 리뷰 개수와 평균 평점, 리뷰 작성일자를 저희가 원하는대로 주입하기가 어려워서 ProductId를 가지고 검증해줬습니다!

2022-08-12 02:45 UTC, Youngyoon-1 commented on backend/src/main/java/com/woowacourse/f12/presentation/inventoryproduct/InventoryProductController.java
>      }
이건 현재 적용하진 않았고, 프론트와 백엔드 다같이 모였을 때 논의해볼까요?

2022-08-12 05:31 UTC, Ohzzi approved these changes

2022-08-12 05:32 UTC, yangdongjue5510 approved these changes
고생하셨습니다.

2022-08-12 05:33 UTC, yh20studio approved these changes

2022-08-12 06:13 UTC, merged