[Feature/BE] 요청 처리 소요 시간 로깅 구현
woowacourse-teams/2022-f12 pull request #467
Opened 2022-08-15 06:08 UTC by yangdongjue5510

# 작업 내용
- Request scope bean을 interceptor에 사용해서 요청의 처리 시간을 측정해서 로깅

2022-08-15 06:58 UTC, yh20studio requested changes
굿굿~ 작은 반영 부탁드립니다

2022-08-15 06:58 UTC, yh20studio commented on backend/src/main/java/com/woowacourse/f12/presentation/LogInterceptor.java
>  public class LogInterceptor implements HandlerInterceptor {
뭔가 저만 그런가요?
읽을때 로그인이라고 먼저 읽히는 듯한 느낌은....
LoggingInterceptor는 어떨지 의견 내봅니다

2022-08-15 06:58 UTC, yh20studio commented on backend/src/test/java/com/woowacourse/f12/support/RequestLogTimerTest.java
> +        assertThat(timeTaken).isGreaterThan(4999);
`isGreaterThanOrEqualTo(5000)` 은 어떨까요?

2022-08-15 06:58 UTC, yh20studio commented on backend/src/test/java/com/woowacourse/f12/support/RequestLogTimerTest.java
> +        assertThat(timeTaken).isGreaterThan(4999);
test가 시간에 종속적인 방법인 것 같아서 의견남깁니다.
현재는 5000 밀리세컨드 때문에 테스트가 모두 5초이상 늘어나게되어있습니다.
그리고 그것 뿐만아니라 테스트 자체가 스프링부트 환경의 시간에 종속된다는 느낌이 들어서 다른 방법을 사용하면 좋을 것 같아요!

2022-08-15 09:52 UTC, Ohzzi requested changes
클레이 칙촉 수고하셨습니다!
하지만 `sleep(5000)`이 있는 한 RC는 계속될겁니다(?)

2022-08-15 09:52 UTC, Ohzzi commented on backend/src/main/java/com/woowacourse/f12/exception/internalserver/IllegalRequestLogTimerState.java
> +public class IllegalRequestLogTimerState extends InternalServerException {
`Exception`은 어디갔죠?

2022-08-15 09:52 UTC, Ohzzi commented on backend/src/test/java/com/woowacourse/f12/support/RequestLogTimerTest.java
> +        requestLogTimer.stop();
이걸 보고 암에 걸렸습니다

2022-08-15 09:52 UTC, Ohzzi commented on backend/src/main/java/com/woowacourse/f12/support/RequestLogTimer.java
> +    }
로그에는 `takenTime`으로 찍히는데 여기서는 `spentTime`이네요?

2022-08-15 10:07 UTC, hamcheeseburger approved these changes
전 잘했다고 생각합니다.

2022-08-16 03:23 UTC, Youngyoon-1 commented on backend/src/main/java/com/woowacourse/f12/presentation/LogInterceptor.java
>  public class LogInterceptor implements HandlerInterceptor {
피드백 감사합니다!! 적용했습니다!

2022-08-16 03:26 UTC, Youngyoon-1 commented on backend/src/test/java/com/woowacourse/f12/support/RequestLogTimerTest.java
> +        assertThat(timeTaken).isGreaterThan(4999);
피드백 주신대로 시간에 종속적이지 않도록 테스트를 재구성했습니다! 피드백 감사합니다~

2022-08-16 03:26 UTC, Youngyoon-1 commented on backend/src/main/java/com/woowacourse/f12/exception/internalserver/IllegalRequestLogTimerState.java
> +public class IllegalRequestLogTimerState extends InternalServerException {
피드백 감사합니다!! 적용했습니다!

2022-08-16 03:26 UTC, Youngyoon-1 commented on backend/src/main/java/com/woowacourse/f12/support/RequestLogTimer.java
> +    }
피드백 감사합니다!!  takenTime으로 통일했습니다!!

2022-08-16 05:43 UTC, yh20studio approved these changes
굳 더 좋아졌네요!

2022-08-16 06:13 UTC, Ohzzi approved these changes

2022-08-16 06:14 UTC, hamcheeseburger approved these changes
굳굳

2022-08-16 06:15 UTC, merged