[Feature/BE] 도메인 로직 리팩토링
woowacourse-teams/2022-f12 pull request #470
Opened 2022-08-15 09:29 UTC by hamcheeseburger

# issue: closes #463 closes #465 

# 작업 내용
- `InventoryProduct`의 일급 컬렉션 구현
- `Member`의 update 로직 하나로 통합

2022-08-15 10:27 UTC, yangdongjue5510 requested changes
좋아요! 하지만 한번 더 생각해주세요!

2022-08-15 10:27 UTC, yangdongjue5510 commented on backend/src/main/java/com/woowacourse/f12/domain/product/Product.java
> +        return this.category == category;
열거형이라 ==를 써도 되지만 equals를 써주세요..

2022-08-15 15:00 UTC, Ohzzi commented on backend/src/main/java/com/woowacourse/f12/domain/product/Product.java
> +        return this.category == category;
Enum의 경우 `equals` 대신 `==`를 사용하는 것이 맞다고 생각합니다.
==를 쓰나 equals를 쓰나 `동일성을 비교`하는 것은 동일한데요, equals의 경우 NPE가 발생할 수 있다는 문제점이 있습니다. 지금 보면 엔티티의 규칙에 의해서는 null이 아닌 것이 보장되지만, 도메인 자체의 validation으로는 null이 보장되지 않죠. 따라서 만약 `Product` 객체의 `Category` 값이 null일 경우, equals를 쓰게 되면 `null.equals`가 되어 NPE가 발생하게 됩니다. 때문에 `==`를 통해 비교하는 것이 더 안전할 것 같네요.
무엇보다 오라클 공식 문서에서 Enum 타입의 비교의 경우 `==`의 사용을 권장하고 있습니다.

2022-08-15 15:38 UTC, yh20studio approved these changes
고생하셨습니다~ 굳굳

2022-08-15 15:38 UTC, yh20studio commented on backend/src/main/java/com/woowacourse/f12/domain/inventoryproduct/InventoryProducts.java
> +    }
이부분이 Member의 `public List<Product> getProfileProducts()`과 연결이 되어서 실행이 되는데,,, 
개인적으로 지금보니깐 대표장비(ProfileProduct)라는 부분이 InventoryProduct에서 `selected==true` 인것이 맞을까 Product가 맞을까라는 생각이 들긴하네요. 기존에 계속 지금처럼 사용이 된 것으로 보이는데, 혹시나 하고 의견남겨봅니다

2022-08-15 15:38 UTC, yh20studio commented on backend/src/main/java/com/woowacourse/f12/domain/inventoryproduct/InventoryProducts.java
> +    }
👍

2022-08-16 01:55 UTC, Youngyoon-1 approved these changes
리펙토링 고생하셨습니다!!

2022-08-16 07:05 UTC, hamcheeseburger commented on backend/src/main/java/com/woowacourse/f12/domain/inventoryproduct/InventoryProducts.java
> +    public InventoryProducts() {
`Member` 에서 `InventoryProduct`를 인스턴스 변수 단위에서 초기화하기 위함인데요,
Member와 InventoryProduct가 같은 패키지 내에 존재하지 않기 때문에 public으로 지정해주었습니다.
그렇다면 인스턴스 변수 단위에서 초기화 할 필요가 있냐는 의문이 드실 수 있는데요,
`Member` 에서 `getProfileProducts()` 를 실행할 때, InventoryProduct가 nullable하다면 추가적인 null 체크가 필요해지기 때문입니다. 안전한 방법으로 인스턴스 변수 단위에서 초기화 하는 것이 올바르다고 판단했습니다.

2022-08-16 07:14 UTC, hamcheeseburger commented on backend/src/test/java/com/woowacourse/f12/acceptance/MemberAcceptanceTest.java
> -
생각해보니 MemberFixtures에 `추가정보를_입력하여_생성()`이 있더라구요, 이를 활용해서 expectedMember를 생성하는 방식으로 변경하였습니다

2022-08-16 07:33 UTC, hamcheeseburger commented on backend/src/main/java/com/woowacourse/f12/domain/inventoryproduct/InventoryProducts.java
> +    }
`List<InventoryProduct> getProfileProducts()` 의 형태로 변경하였습니다

2022-08-16 09:03 UTC, yangdongjue5510 approved these changes

2022-08-16 10:25 UTC, merged