[Feature/BE] 인수 테스트 리팩토링
woowacourse-teams/2022-f12 pull request #588
Opened 2022-09-14 12:05 UTC by Ohzzi

# issue: closes #533 

# 작업 내용
- 인수 테스트 리팩토링 완료
  - 인수 테스트 내부 동작들이 문장형으로 읽히도록 테스트 수정
  - 인수 테스트용 테스트 픽스처 새로 생성

2022-09-14 14:03 UTC, yangdongjue5510 approved these changes
아주 훌륭합니다! 오찌 고생하셨어요!
다만 코멘트 확인해주시고 수정해주세용~

2022-09-15 04:43 UTC, hamcheeseburger approved these changes
수고하셨슴니다

2022-09-15 04:43 UTC, hamcheeseburger commented on backend/src/test/java/com/woowacourse/f12/acceptance/InventoryProductAcceptanceTest.java
> +        CORINNE.로그인한_상태로(token).리뷰를_작성한다(productId, REVIEW_RATING_5);
```suggestion
        AuthorizedAction 로그인한_상태로 = CORINNE.로그인한_상태로(token);
        로그인한_상태로.추가정보를_입력한다(memberRequest);
        로그인한_상태로.리뷰를_작성한다(productId, REVIEW_RATING_5);
```

2022-09-15 05:13 UTC, yh20studio requested changes
오찌 테스트 코드 수정하느라 고생 많으셨습니다. 
변경 사항과 이야기할 부분이 있으니 RC 남기겠습니다!

2022-09-15 05:48 UTC, Youngyoon-1 approved these changes
오찌 덕분에 테스트 코드 가독성이 매우 좋아졌네요. 감사합니다. 굿

2022-09-15 05:48 UTC, Youngyoon-1 commented on backend/src/test/java/com/woowacourse/f12/acceptance/MemberAcceptanceTest.java
> +    void 로그인_하고_회원목록을_검색한다() {
테스트 이름을 조금 더 구체적으로 로그인_하고_다른회원을_팔로우한뒤_회원목록을_검색한다 는 어떨까요?!

2022-09-15 05:48 UTC, Youngyoon-1 commented on backend/src/test/java/com/woowacourse/f12/acceptance/MemberAcceptanceTest.java
> +    void 로그인_하고_팔로우하는_회원의_목록을_검색하여_조회한다() {
테스트 이름을 로그인_하고_팔로우하는_회원의_목록을_검색조건_설정해서_조회한다 는 어떨까요?!

2022-09-15 07:49 UTC, yh20studio approved these changes
아주~좋아요!

2022-09-15 08:40 UTC, merged