[FE] 프로필 페이지에 리뷰 목록을 출력하는 기능 구현
woowacourse-teams/2022-f12 pull request #595
Opened 2022-09-16 07:18 UTC by jswith

# 작업 내용

2022-09-18 04:21 UTC, uk960214 requested changes
프로필 페이지에 있는 리뷰에서 사용자 정보는 계속해서 같은 사용자가 작성한 글이기 때문에 리뷰 카드에서 사용자 정보를 제외하기로 했던 것 같은데 그것까지 혹시 처리 가능하면 처리 부탁드립니다! 나머지는 확인했습니다!!

2022-09-18 04:21 UTC, uk960214 commented on frontend/src/components/DeskSetupCard/DeskSetupCard.tsx
> +    <S.Container index={0} size={size} borderType={borderType} isEditMode={isEditMode}>
이건 동시에 애니메이션이 적용되는걸 바라서 고정 값으로 준 것 맞나요?

2022-09-18 04:21 UTC, uk960214 commented on frontend/src/hooks/useInventory.tsx
> +  isReviewError: boolean;
프로필 별 리뷰를 다른 훅으로 빼지 않고 함께 인벤토리 훅에 넣은 이유가 있나요?

2022-09-19 04:02 UTC, jswith commented on frontend/src/hooks/useInventory.tsx
> +  isReviewError: boolean;
Review vs Inventory

어디에 넣을지 고민을 하다가 Inventory 내부에서만 호출되는 리뷰 목록 + 
새로운 훅으로 뺴기에는 네이밍이 애매해서 Inventory에 넣었습니다.

2022-09-19 04:04 UTC, jswith commented on frontend/src/components/DeskSetupCard/DeskSetupCard.tsx
> +    <S.Container index={0} size={size} borderType={borderType} isEditMode={isEditMode}>
index의 역할을 잘못 알고 있었네요~ 리뷰 리스트와 통일성을 위해 순차적 애니메이션을 주는 것이 맞는 것 같습니당

2022-09-19 05:03 UTC, jswith commented on frontend/src/components/DeskSetupCard/DeskSetupCard.tsx
> +    <S.Container index={0} size={size} borderType={borderType} isEditMode={isEditMode}>
[ad8da05](https://github.com/woowacourse-teams/2022-f12/pull/595/commits/ad8da05030d4031051ecb8a56cc059bff35080d3)

2022-09-19 05:13 UTC, uk960214 commented on frontend/src/hooks/useInventory.tsx
> +  isReviewError: boolean;
일단 현재 구조를 크게 변경하지 않는 선에서는 이 방법이 최선인 것 같네요! 추후에 리팩토링 하면서 다시 자세히 논의해보도록 하시죠!

2022-09-19 05:14 UTC, uk960214 approved these changes
수고하셨습니다!

2022-09-19 05:14 UTC, uk960214 commented on frontend/src/components/DeskSetupCard/DeskSetupCard.tsx
> +      index={index}
굿굿

2022-09-19 05:15 UTC, merged