[Feature/BE] refresh 토큰을 도입
woowacourse-teams/2022-f12 pull request #599
Opened 2022-09-16 13:46 UTC by yangdongjue5510

# issue: closes #572

# 작업 내용
- 토큰의 유무에 따라서 변경되는 API에 대해서 `AuthInterceptor`를 일괄적으로 사용하기 위해서 `@LoginRequired`를 `@Login`으로 바꾸고 required 속성을 추가해서 required가 false이고 토큰이 없는 경우(비회원인 경우)에는 토큰 유효성 검사를 건너뛰도록 구현.
- 로그인 API에 성공하는 경우 access token과 refresh token을 반환
    - access token은 기존과 동일하게 바디에 담음.
    - refresh token은  cookie(http-only, secure)에 담음
- refresh token이 생성되면 인메모리 저장소에 유효기간과 memberId를 refresh token과 함께 저장한다.
- refresh token으로 access token을 발급받는다.
    - refresh token도 같이 발급되고 삭제된다.
    - refresh token이 만료된 경우 쿠키를 삭제하고 예외 발생한다.
    - refresh token이 저장되어 있지 않은 값일 경우 예외를 발생한다.

# 주의사항
인메모리 저장소를 다룰 때는 트랜잭션 적용되지 않는다. (액세스 토큰 재발급 로직에는 위험할 수 있다.)

<img width="993" alt="스크린샷 2022-09-16 오후 10 41 16" src="https://user-images.githubusercontent.com/87690744/190653505-bde72d83-9802-426d-ac33-41ebb79d6930.png">

2022-09-16 16:37 UTC, Youngyoon-1 approved these changes

2022-09-16 16:37 UTC, Youngyoon-1 commented on backend/src/main/java/com/woowacourse/f12/presentation/GlobalExceptionHandler.java
> +                                                                                 HttpServletResponse response) {
final 키워드가 빠져있네용

2022-09-16 16:38 UTC, Youngyoon-1 commented on backend/src/main/java/com/woowacourse/f12/presentation/GlobalExceptionHandler.java
> +                                                                                 HttpServletResponse response) {
final 키워드가 빠졌네용

2022-09-16 17:25 UTC, Youngyoon-1 reviewed
이런 AccessToken의 유효기간이 expire-length: 3600000 1시간이군요.

2022-09-18 05:05 UTC, Ohzzi requested changes
수고 많았습니다 클레이 칙촉~~
좀 더 고려하고 코드를 개선할 만한 부분이 있어서 RC 드릴게요 확인해주세요 :)

2022-09-18 05:05 UTC, Ohzzi commented on backend/src/main/java/com/woowacourse/f12/presentation/auth/AuthInterceptor.java
> +        validateTokenRequired(handler);
이거 그러면 로직이
- Authorization 헤더가 있다 -> 무조건 토큰 유효성을 검증한다
- Authorization 헤더가 없다 -> 요청받은 메서드가 로그인이 필요한 작업인지 검증한다

이 플로우를 따르는게 맞는거겠죠?

2022-09-18 16:28 UTC, yh20studio requested changes
고생하셨습니다! 로직적으로는 구현이 너무 잘된 거 같네요! 어려워 보였는데 잘 풀어나간거 같습니다
다만 트랜잭션등 문제가 있지만, 좋습니다!! 다만, class 이름 등 가독성적인 측면에서 리뷰를 남겼으니 확인해보고 답변주시면 감사하겠습니다!

2022-09-18 16:28 UTC, yh20studio commented on backend/src/main/java/com/woowacourse/f12/presentation/review/ReviewController.java
>                                                                              final Pageable pageable) {
여기도 @VerifiedMember Long memberId 부분에서 @Nullable 이 붙는게 MemberController와 통일성을 지닐 수 있다고 생각합니다.

2022-09-18 16:28 UTC, yh20studio commented on backend/src/test/java/com/woowacourse/f12/acceptance/AuthAcceptanceTest.java
> +        final ExtractableResponse<Response> refreshTokenResponse = RestAssured.given().log().all()
final 이 들어갔네요!

2022-09-18 16:28 UTC, yh20studio commented on backend/src/test/java/com/woowacourse/f12/application/auth/RefreshTokenInfoTest.java
> +    }
예외가 발생하는 상황은 아닌 것 같습니다!

2022-09-18 16:28 UTC, yh20studio commented on backend/src/test/java/com/woowacourse/f12/presentation/auth/AuthControllerTest.java
> +                .andDo(print());
👍 👍 👍 👍 👍 👍

2022-09-18 16:28 UTC, yh20studio commented on backend/src/test/java/com/woowacourse/f12/presentation/auth/AuthInterceptorTest.java
> +        );
좋네요 이부분이 이전에, 리뷰에서 에러가 났던 부분인거 같네요 👍 👍 👍

2022-09-19 06:04 UTC, yangdongjue5510 commented on backend/src/main/java/com/woowacourse/f12/application/auth/InmemoryRefreshTokenRepository.java
> +    }
token 자체가 Null이 아닌 경우에는 NPE가 터지지 않습니다. 해당 token 값이 Key에 없다면 NPE 대신 null을 반환합니다.

2022-09-19 06:07 UTC, yangdongjue5510 commented on backend/src/main/java/com/woowacourse/f12/application/auth/RefreshTokenInfo.java
> +    }
적용했습니다.

2022-09-19 06:08 UTC, yangdongjue5510 commented on backend/src/main/java/com/woowacourse/f12/dto/response/auth/IssuedTokensResponse.java
> +    }
적용했습니다.

2022-09-19 07:16 UTC, yangdongjue5510 commented on backend/src/main/java/com/woowacourse/f12/dto/response/auth/TokenResponse.java
> +    private final LoginResponse loginResponse;
웹 응답에 사용되는 DTO와 서비스에서 로직 결과물을 반환하는 Result 객체를 분리해서 반영하도록 하겠습니다.

2022-09-19 07:17 UTC, yangdongjue5510 commented on backend/src/main/java/com/woowacourse/f12/presentation/auth/AuthInterceptor.java
> +        validateTokenRequired(handler);
정확합니다. 🙆‍

2022-09-19 07:19 UTC, yangdongjue5510 commented on backend/src/main/java/com/woowacourse/f12/presentation/review/ReviewController.java
>                                                                              final Pageable pageable) {
반영했습니다.

2022-09-19 07:21 UTC, yangdongjue5510 commented on backend/src/main/java/com/woowacourse/f12/presentation/GlobalExceptionHandler.java
> +        final Cookie refreshToken = WebUtils.getCookie(request, "refreshToken");
반영했습니다.

2022-09-19 07:23 UTC, yangdongjue5510 commented on backend/src/main/java/com/woowacourse/f12/presentation/GlobalExceptionHandler.java
> +        assert refreshToken != null;
조건에 맞지 않는다면 AssertionError가 발생합니다.

2022-09-19 07:24 UTC, yangdongjue5510 commented on backend/src/main/java/com/woowacourse/f12/presentation/GlobalExceptionHandler.java
> +                                                                                 HttpServletResponse response) {
반영했습니다.

2022-09-19 07:30 UTC, yangdongjue5510 commented on backend/src/main/java/com/woowacourse/f12/presentation/GlobalExceptionHandler.java
> +                                                                                 HttpServletResponse response) {
현재 엑세스 토큰에서 형식이 맞지 않으면 TokenInvalidException이 발행합니다. 말씀하신 부분을 적용하게 되면  Invalid 의미가 사용될것 같습니다.

2022-09-19 07:33 UTC, yangdongjue5510 commented on backend/src/main/java/com/woowacourse/f12/presentation/GlobalExceptionHandler.java
> +                                                                                 HttpServletResponse response) {
넵 RefreshTokenInvalidException 으로 수정했습니다!

2022-09-19 07:34 UTC, yangdongjue5510 commented on backend/src/main/java/com/woowacourse/f12/presentation/GlobalExceptionHandler.java
> +        return handleUnauthorizedException(e);
😃

2022-09-19 07:35 UTC, yangdongjue5510 commented on backend/src/test/java/com/woowacourse/f12/acceptance/AuthAcceptanceTest.java
> +        final ExtractableResponse<Response> refreshTokenResponse = RestAssured.given().log().all()
반영했습니다.!

2022-09-19 07:35 UTC, yangdongjue5510 commented on backend/src/test/java/com/woowacourse/f12/application/auth/RefreshTokenInfoTest.java
> +    }
예외가 발생한다 대신에 판별한다 로 수정했습니다.

2022-09-19 10:14 UTC, yangdongjue5510 commented on backend/src/main/java/com/woowacourse/f12/application/auth/AuthService.java
> +    private static final int REFRESH_TOKEN_EXPIRED_DAYS = 14;
yaml 파일로 관리하도록 수정하겠습니다.

2022-09-19 10:15 UTC, yangdongjue5510 commented on backend/src/main/java/com/woowacourse/f12/application/auth/AuthService.java
>      private final JwtProvider jwtProvider;
상수를 제거했습니다.

2022-09-19 10:15 UTC, yangdongjue5510 commented on backend/src/main/java/com/woowacourse/f12/application/auth/AuthService.java
> +        final String refreshToken = refreshTokenProvider.createToken();
RefreshToken을 사용하도록 수정하겠습니다.

2022-09-19 10:16 UTC, yangdongjue5510 commented on backend/src/main/java/com/woowacourse/f12/application/auth/AuthService.java
> +        refreshTokenRepository.save(refreshToken, RefreshTokenInfo.createByExpiredDay(member.getId(), 14));
yaml 파일로 관리하도록 하겠습니다.

2022-09-19 10:16 UTC, yangdongjue5510 commented on backend/src/main/java/com/woowacourse/f12/application/auth/AuthService.java
> +                .orElseThrow(RefreshTokenNotFoundException::new);
RefreshToken 클래스를 추가해서 RefreshTokenInfo를 제거했습니다.

2022-09-19 10:17 UTC, yangdongjue5510 commented on backend/src/main/java/com/woowacourse/f12/application/auth/AuthService.java
> +        final String newAccessToken = jwtProvider.createToken(memberId);
반영했습니다.

2022-09-19 10:17 UTC, yangdongjue5510 commented on backend/src/main/java/com/woowacourse/f12/application/auth/RefreshTokenProvider.java
> +}
반영했습니다.

2022-09-19 10:18 UTC, yangdongjue5510 commented on backend/src/main/java/com/woowacourse/f12/presentation/auth/AuthInterceptor.java
> +    private Login getLogin(final Object handler) {
반영했습니다.

2022-09-19 11:22 UTC, yh20studio approved these changes
고생하셨습니다!!!

2022-09-19 11:51 UTC, Ohzzi approved these changes

2022-09-19 15:49 UTC, merged