Feature/be/http client
woowacourse-teams/2022-f12 pull request #684
Opened 2022-09-29 05:35 UTC by yangdongjue5510

# issue: #681 

# 작업 내용
- WebClient를 HttpClient로 변경
- webFlux 의존성 제거

2022-09-29 07:01 UTC, yh20studio approved these changes
아주 좋은 PR이네요! 고생하셨습니다 클레이!

2022-09-29 07:44 UTC, Youngyoon-1 approved these changes
고생하셨습니다!!

2022-09-29 07:50 UTC, hamcheeseburger approved these changes
수고하셨습니다 끌레이 👍🏻

2022-09-29 07:50 UTC, hamcheeseburger commented on backend/src/main/java/com/woowacourse/f12/application/auth/GitHubOauthClient.java
> +                .POST(HttpRequest.BodyPublishers.ofString(requestBody))
메소드 순서 호출 순으로 정리하는게 나을 것 같다는 생각입니다 !!

2022-09-29 10:05 UTC, Ohzzi requested changes
수고하셨습니다 몇가지 생각해볼 부분 남겼으니 RC날릴게요^^

2022-09-29 13:15 UTC, yangdongjue5510 commented on backend/src/main/java/com/woowacourse/f12/application/auth/GitHubOauthClient.java
> +            .version(Version.HTTP_1_1)
일단 HTTP 2.0으로 사용해보고 테스트 서버에서 QA 해보는게 좋을 것 같습니다.

2022-09-29 13:23 UTC, yangdongjue5510 commented on backend/src/test/java/com/woowacourse/f12/application/auth/AuthServiceTest.java
> +    private GitHubOauthClient oauthClient;
다시 돌려놓겠습니다.

2022-09-30 02:12 UTC, yangdongjue5510 commented on backend/src/main/java/com/woowacourse/f12/application/auth/GitHubOauthClient.java
> +                .uri(toURI(accessTokenUrl))
빌더에 uri를 인자로 전달하도록 수정하겠습니다.

2022-09-30 02:15 UTC, yangdongjue5510 commented on backend/src/main/java/com/woowacourse/f12/application/auth/GitHubOauthClient.java
> +    private final ObjectMapper objectMapper = new ObjectMapper();
공백 기준으로 생성자에서 주입받는 인스턴스 필드와 클래스 내부에서 인스턴스를 생성해서 초기화하는 인스턴스 필드 두가지로 나누기 위해서 공백을 두었습니다. 오찌는 어떻게 생각하나용

2022-09-30 02:26 UTC, yangdongjue5510 commented on backend/src/main/java/com/woowacourse/f12/application/auth/GitHubOauthClient.java
> +                .POST(HttpRequest.BodyPublishers.ofString(requestBody))
메서드 순서 호출 순서 순으로 메서드를 정의하겠습니다.

2022-09-30 02:26 UTC, yangdongjue5510 commented on backend/src/main/java/com/woowacourse/f12/application/auth/GitHubOauthClient.java
> +    private void validateStatus(final HttpResponse<String> response) {
반영하겠습니다.

2022-09-30 06:36 UTC, Ohzzi approved these changes
좋습니다

2022-09-30 06:39 UTC, merged