[Feature/BE] 각 도메인 테이블에 unique 제약 조건을 추가한다 (#688)
woowacourse-teams/2022-f12 pull request #689
Opened 2022-09-29 06:50 UTC by hamcheeseburger

# 작업 내용
- unique 제약조건에 대한 테스트 추가
- ControllerAdvice에 unique 관련 Exception 처리
- Main, Release DB에 제약조건 추가

아래는 Main DB에 적용된 제약 조건입니다.
UNIQUE 관련한 제약조건이 추가되었습니다.

<img width="1266" alt="스크린샷 2022-09-29 15 48 34" src="https://user-images.githubusercontent.com/61769743/192959313-56e58242-2875-4e99-9a57-251d82242d67.png">

2022-09-29 07:58 UTC, Youngyoon-1 approved these changes
고생하셨습니다!

2022-09-29 10:16 UTC, Ohzzi requested changes
수고했습니다 코린~ 간단하지만 생각해볼 필요가 있는 부분이 있어 RC 남길게요!

2022-09-29 10:16 UTC, Ohzzi commented on backend/src/main/java/com/woowacourse/f12/domain/inventoryproduct/InventoryProduct.java
> +                columnNames = {"product_id", "member_id"})})
유니크 제약 조건 이름과 컬럼 순서가 안맞는 👀

2022-09-29 10:16 UTC, Ohzzi commented on backend/src/main/java/com/woowacourse/f12/presentation/GlobalExceptionHandler.java
> +    private static final String DATA_DUPLICATED_MESSAGE = "값이 중복될 수 없습니다";
값이 중복되는 것 보다는 요청이 중복되었다고 하는 것이 맞지 않을까요?

2022-09-29 10:16 UTC, Ohzzi commented on backend/src/test/java/com/woowacourse/f12/domain/inventoryproduct/InventoryProductRepositoryTest.java
> +
DB 유니크에 의존하는 테스트가 과연 꼭 필요한 테스트일까요? 👀

2022-09-30 01:25 UTC, yh20studio approved these changes
안녕하세요 코린 DB 유니크 설정 고생하셨습니다. 로직과는 큰 상관없는 리뷰 몇개 남겼습니다
마지막으로 Main, Release, Performance DB 모두 적용이 되었는지 확인 하고 머지 부탁드리겠습니다!

2022-09-30 01:25 UTC, yh20studio commented on backend/src/docs/asciidoc/auth.adoc
> +- 40002, 50001, 40060
40002, 40060, 50001 순서가 좋을 거 같습니다!

2022-09-30 01:25 UTC, yh20studio commented on backend/src/docs/asciidoc/members.adoc
> +- 40050, 40051, 40410, 40060
여기도 400끼리 먼저 적으면 좋을 것 같네요

2022-09-30 01:25 UTC, yh20studio commented on backend/src/docs/asciidoc/reviews.adoc
> +- 40030, 40031, 40032, 40033, 40100, 40101, 40102, 40103, 40060
마찬가지입니다!

2022-09-30 01:25 UTC, yh20studio commented on backend/src/test/java/com/woowacourse/f12/domain/inventoryproduct/InventoryProductRepositoryTest.java
> +
저는 개인적으로 `@Entity`에 유니크 조건을 DB에서만 걸어준 것이 아니라, unique 제약조건을 명시하고 있기 때문에 테스트를 하는 것이 좋아보입니다

2022-09-30 02:23 UTC, hamcheeseburger commented on backend/src/test/java/com/woowacourse/f12/domain/inventoryproduct/InventoryProductRepositoryTest.java
> +
테스트가 로직이 잘 동작하는지 확인하는 용도도 있지만, 이러한 부분까지 대처했다는 것을 명시적으로 보여주는 효과도 있다고 생각합니다.
`@Entity`에 제약조건을 추가한 것도 동일한 이유 이고요!

2022-09-30 06:34 UTC, yangdongjue5510 approved these changes

2022-09-30 06:34 UTC, yangdongjue5510 commented on backend/src/test/java/com/woowacourse/f12/domain/inventoryproduct/InventoryProductRepositoryTest.java
> +
저도 티키, 코린 의견에 동의합니다.

2022-09-30 06:34 UTC, yangdongjue5510 commented on backend/src/test/java/com/woowacourse/f12/domain/member/FollowingRepositoryTest.java
> +        // when, then
공백을 주는건 어떨까요

2022-09-30 06:37 UTC, Ohzzi approved these changes

2022-10-03 02:33 UTC, merged