[Bugfix/BE] local 환경에서 Repository 테스트시 쿼리 로그가 2번 남는 현상 해결
woowacourse-teams/2022-f12 pull request #696
Opened 2022-09-29 10:19 UTC by yh20studio

# 작업 내용
local 환경에서 respository test 시 쿼리 로그가 2번 남는 현상 수정

1. 처음에는 JPA의 로그를 활용하지 않고, log4j2의 로그를 활용하도록 수정하려고 했으나, format_sql이 지켜지지 않고 한줄로 나옴.
-> 실패
2. format_sql = true & show_sql=false로 설정하더라도 해당 현상이 해결되지 않음. (show-sql 설정이 무시되는 것 같음)
-> 실패
3. local 환경에서는 log4j2의 sql 로그를 활용하지 않고, JPA의 로그를 활용하려고 했음. Repository Test에서 쿼리 로그가 2번 남는 현상은 고쳐졌지만, release, main 환경에서 log4j2의 로그는 파일에 남겨지고 있지만, JPA의 로그는 스프링 부트 로그에 남고 있을 것이라 판단(nohup.output 에 기록되고 있을 것이다.)
-> 완벽하지 않은 성공

따라서 log4j2의 로그를 활용하기로 하고, JPA의 로그 남기는 옵션을 끄기로 했음.
방법은 문제가 되는 `@DataJpaTest` 어노테이션을 사용하는 테스트에서 show-sql을 false로 설정

2022-09-29 11:33 UTC, Ohzzi approved these changes
크게 리뷰할 부분이 없네요! 고생하셨습니다 :)

2022-09-29 12:46 UTC, yangdongjue5510 requested changes
고생하셨습니다 티키!
코멘트 한번 확인해주세요!

2022-09-29 12:46 UTC, yangdongjue5510 commented on backend/src/main/resources/application.yml
> -    show-sql: true
여기서 show-sql: true를 제거해주는 이유는 로컬로 어플리케이션을 돌렸을 때 로그에 쿼리 로그가 2번 남기 때문인가용??

2022-09-29 12:46 UTC, yangdongjue5510 commented on backend/src/test/java/com/woowacourse/f12/domain/inventoryproduct/InventoryProductRepositoryTest.java
> +@DataJpaTest(showSql = false)
application.yml에도 showSql:true를 제거하고 DataJpaTest에도 showSql을 false로 했네욧,,
이 두가지 처리가 각 어떤 효과를 만드나요?

2022-09-29 12:46 UTC, yangdongjue5510 commented on backend/src/test/java/com/woowacourse/f12/domain/inventoryproduct/InventoryProductRepositoryTest.java
> +@DataJpaTest(showSql = false)
그리고 매번 `@DataJpaTest(showSql = false)` 를 써주는 것도 좋은데 RepositoryTest 클래스를 만들어서 그 곳에서 `@DataJpaTest(showSql = false)`로 하고 실제 레포지토리 테스트 클래스들은 RepositoryTest를 상속받아서 사용하면 어떨까요??

2022-09-30 07:07 UTC, hamcheeseburger approved these changes
수고하셨습니다 티키~!! 👍🏻

2022-09-30 07:07 UTC, hamcheeseburger commented on backend/src/test/java/com/woowacourse/f12/domain/inventoryproduct/InventoryProductRepositoryTest.java
> +@DataJpaTest(showSql = false)
클레이 의견에 동의합니다 ~!

2022-10-03 11:56 UTC, yangdongjue5510 approved these changes
새로운 어노테이션을 구현한 방식이 정말 좋네요! 고생하셨습니다 티키!!!

2022-10-03 17:55 UTC, Youngyoon-1 approved these changes
티키 고생하셨습니다!

2022-10-03 17:55 UTC, Youngyoon-1 commented on backend/src/test/java/com/woowacourse/f12/domain/RepositoryTest.java
> +public @interface RepositoryTest {
역시 테스트 장인이십니다👍

2022-10-04 01:26 UTC, merged