[Feature/be] 인증 인가 수정
woowacourse-teams/2022-f12 pull request #699
Opened 2022-09-29 13:47 UTC by Ohzzi

# issue: closes #577 closes #698 

# 작업 내용
### 회원에게 Role 부여
- Member에 Role 필드 추가
- @VerifiedMember의 대상 타입 Long -> MemberPayload 변경
  - MemberPayload는 id와 Role을 가지고 있음
- JWT가 Payload 객체로 변환할 때 자동으로 타입 변환해줌
  - 기존처럼 NumberFormatException을 잡는 것이 아니라 RequiredTypeException을 잡아서 TokenInvalidFormatException으로 바꿔줌
### JWT 생성 방식 변경
- JWT의 subject에는 "AccessToken" 이라는 값을 넣어 토큰의 주제를 표시
- subject 대신 claim에 payload를 저장
- payload를 꺼낼 때 subject가 "AccessToken" 인지 검증
- payload를 claims에서 꺼냄

2022-09-30 02:40 UTC, yh20studio requested changes
오찌 테스트 수정하느라 너무 고생많으셨습니다. 간단한 리뷰 몇개남겼습니다. 다른 거는 크게 문제될게 없어 보이는데 DB 관련하여 설정에 대한 의견 때문에 RC 드리겠습니다!

2022-09-30 02:40 UTC, yh20studio commented on backend/src/main/java/com/woowacourse/f12/domain/member/Member.java
> +
`@Enumerated`의 EnumType의 default 값이 ordinal 로 알고 있습니다. 이렇게 되면 DB에 0, 1 이렇게 저장이 될듯 한데 `@Enumerated(EnumType.STRING)` 으로 하는 것은 어떨까요?

2022-09-30 02:40 UTC, yh20studio commented on backend/src/main/java/com/woowacourse/f12/application/auth/token/JwtProvider.java
> +                .setSubject(ACCESS_TOKEN_SUBJECT)
Subject에 ACCESS_TOKEN_SUBJECT = "AccessToken" 을 넣어주는 이유는 무엇인가요?

2022-09-30 02:40 UTC, yh20studio commented on backend/src/main/java/com/woowacourse/f12/application/auth/token/JwtProvider.java
> +                .getBody();
.getBody() 한줄로 써도 될 것 같습니다~

2022-09-30 02:40 UTC, yh20studio commented on backend/src/main/java/com/woowacourse/f12/application/auth/token/JwtProvider.java
> +        }
RequiredTypeException에서 "role"이 null인 것도 잡아주는 것일까요? 그리고 Role.valueOf() 에서 IllegalArgumentException과, NPE에 대해서는 잡아주지 않아도 괜찮을까요?

2022-09-30 02:40 UTC, yh20studio commented on backend/src/main/java/com/woowacourse/f12/presentation/member/MemberController.java
> +        return loggedInMemberPayload.getId();
해당 메서드를 MemberPayload 내부에서 구현하는 것은 어땠을까요?

2022-09-30 02:40 UTC, yh20studio commented on backend/src/test/java/com/woowacourse/f12/application/auth/token/JwtProviderTest.java
> +                .isExactlyInstanceOf(TokenInvalidFormatException.class);
테스트 잘하셨네요! 👍 Role이 잘못된 경우도 테스트를 해볼 수 있을까요?

2022-09-30 06:17 UTC, hamcheeseburger approved these changes
오찌 수고하셨습니다~!!

2022-09-30 06:17 UTC, hamcheeseburger commented on backend/src/main/java/com/woowacourse/f12/presentation/member/MemberController.java
> +        Long id = getLoggedInMemberId(loggedInMemberPayload);
변수명 loggedInMemberId로 하는게 좋을 것 같아요 ~!

2022-09-30 06:18 UTC, yangdongjue5510 approved these changes
까다로웠을 것 같은데 잘하셨네요!
코멘트 한번만 확인해주세요!
고생하셨습니다!!!

2022-09-30 06:18 UTC, yangdongjue5510 commented on backend/src/main/java/com/woowacourse/f12/presentation/member/MemberController.java
> +    private Long getLoggedInMemberId(@Nullable final MemberPayload loggedInMemberPayload) {
이 메서드도 호출 순서대로 구현하는 건 어떤가용

2022-09-30 06:18 UTC, yangdongjue5510 commented on backend/src/main/java/com/woowacourse/f12/presentation/review/ReviewController.java
> +    }
이 로직이 MemberPayload가 쓰이는 곳마다 있는 것 같네요. 중복을 줄일 방법은 없을까욧?

2022-09-30 07:24 UTC, Youngyoon-1 approved these changes
고생하셨습니다!!

2022-10-02 01:46 UTC, Ohzzi commented on backend/src/main/java/com/woowacourse/f12/application/auth/token/JwtProvider.java
> +                .setSubject(ACCESS_TOKEN_SUBJECT)
토큰 검증을 이왕 하는 김에 토큰 이름도 넣어주자라고 생각했습니다 :)

2022-10-02 01:47 UTC, Ohzzi commented on backend/src/main/java/com/woowacourse/f12/application/auth/token/JwtProvider.java
> +        }
따로 잡아줘야 할 것 같네요...!

2022-10-02 01:47 UTC, Ohzzi commented on backend/src/main/java/com/woowacourse/f12/presentation/member/MemberController.java
> +        return loggedInMemberPayload.getId();
MemberPayload 자체의 null 체크를 해야 하기 때문에 불가능할 것 같아요 :)

2022-10-02 01:49 UTC, Ohzzi commented on backend/src/main/java/com/woowacourse/f12/application/auth/token/JwtProvider.java
> +                .addClaims(claims)
처음엔 이렇게 했었는데, 생각해보니 두 개 정도는 그래도 괜찮을 것 같네요 :)

2022-10-02 01:49 UTC, Ohzzi commented on backend/src/main/java/com/woowacourse/f12/presentation/review/ReviewController.java
> +    }
유틸 클래스로 분리하겠습니다

2022-10-02 03:33 UTC, Ohzzi commented on backend/src/main/java/com/woowacourse/f12/application/auth/token/JwtProvider.java
> +                .after(new Date());
아쉽게도 JwtBuilder 클래스가 Date 타입만 받는 것 같아요 😢

2022-10-03 09:57 UTC, yh20studio approved these changes
리뷰반영하신거 확인했습니다 오찌 고생했습니다

2022-10-03 11:16 UTC, merged