[Feature/BE] 어드민 API 구현
woowacourse-teams/2022-f12 pull request #710
Opened 2022-10-04 08:09 UTC by yangdongjue5510

# issue: closes#597 

# 작업 내용
- 제품 추가, 수정, 삭제 API 구현
- 어드민 인증 인가 로직을 AuthInterceptor에 추가

2022-10-04 09:46 UTC, yh20studio requested changes
클레이, 코린 고생많았습니다. 리뷰 간단하게 남겼으니 확인 부탁드립니다! 😄

2022-10-04 09:46 UTC, yh20studio commented on backend/src/main/java/com/woowacourse/f12/application/product/ProductService.java
>          this.productRepository = productRepository;
final 키워드가 빠졌네요!

2022-10-04 09:46 UTC, yh20studio commented on backend/src/main/java/com/woowacourse/f12/dto/request/product/ProductCreateRequest.java
> +    private String imageUrl;
레이디가가~

2022-10-04 09:46 UTC, yh20studio commented on backend/src/main/java/com/woowacourse/f12/domain/product/Product.java
> +
물론 DTO에서 Notnull이 검증이되었지만, Product 단위로만 본다면 null 체크가 이루어져야하지 않을까요?

2022-10-04 09:46 UTC, yh20studio commented on backend/src/main/java/com/woowacourse/f12/dto/request/product/ProductUpdateRequest.java
> +
여기도 `가가` 네요

2022-10-04 09:46 UTC, yh20studio commented on backend/src/main/java/com/woowacourse/f12/exception/ErrorCode.java
> +    INACCESSIBLE("40107"),
에러 코드가 403 아닐까요?

2022-10-04 09:46 UTC, yh20studio commented on backend/src/main/java/com/woowacourse/f12/presentation/auth/AuthInterceptor.java
> +@Order(1)
필요 없어 보입니다! 삭제 부탁드릴게요

2022-10-04 09:46 UTC, yh20studio commented on backend/src/main/java/com/woowacourse/f12/presentation/auth/AuthInterceptor.java
> +
좋네요 메서드 선언 순서만 정리해주면 될 것 같아요!

2022-10-04 09:46 UTC, yh20studio commented on backend/src/test/java/com/woowacourse/f12/acceptance/ProductAcceptanceTest.java
> +        );
assertAll 이 필요없어보이네요!

2022-10-04 09:46 UTC, yh20studio commented on backend/src/test/java/com/woowacourse/f12/acceptance/ProductAcceptanceTest.java
> +        );
여기도 마찬가지 입니다

2022-10-04 09:46 UTC, yh20studio commented on backend/src/test/java/com/woowacourse/f12/application/product/ProductServiceTest.java
> +                () -> assertThatThrownBy(() -> productService.update(1L, productUpdateRequest)),
어떤 Exception 타입을 던지는지 검증하면 좋을 것 같습니다

2022-10-04 09:46 UTC, yh20studio commented on backend/src/test/java/com/woowacourse/f12/application/product/ProductServiceTest.java
> +                () -> assertThatThrownBy(() -> productService.delete(1L)),
어떤 Exception 타입을 던지는지 검증하면 좋을 것 같습니다

2022-10-04 09:46 UTC, yh20studio commented on backend/src/test/java/com/woowacourse/f12/presentation/product/ProductControllerTest.java
> +        resultActions.andExpect(status().isUnauthorized());
개인적으로 일반계정으로 로그인했을 때 실패하는 테스트를 `AuthInterceptorTest`에서 수행해야하지 않나 싶습니다!

2022-10-04 10:29 UTC, Ohzzi requested changes
수고하셨습니다! 몇 군데 리뷰 남겼으니 확인해주세요:)

2022-10-04 10:29 UTC, Ohzzi commented on backend/src/main/java/com/woowacourse/f12/exception/unauthorized/InaccessibleException.java
> +public class InaccessibleException extends UnauthorizedException {
ForbiddenException을 그대로 사용해도 되지 않을까요? 아니면 NotAdminException 정도여도 좋을 것 같네요

2022-10-04 10:29 UTC, Ohzzi commented on backend/src/main/java/com/woowacourse/f12/presentation/auth/Login.java
> +    boolean admin() default false;
👍

2022-10-04 10:29 UTC, Ohzzi commented on backend/src/main/java/com/woowacourse/f12/presentation/product/ProductController.java
> +        return ResponseEntity.noContent().build();
위 메서드들처럼 여기도 개행 들어가면 좋을 것 같아요 :)

2022-10-04 10:29 UTC, Ohzzi commented on backend/src/main/java/com/woowacourse/f12/domain/inventoryproduct/InventoryProductRepository.java
> +    void deleteByProduct(Product target);
이 메서드에 대한 repository 테스트도 만드는게 어떨까요?

2022-10-04 10:29 UTC, Ohzzi commented on backend/src/main/java/com/woowacourse/f12/domain/review/ReviewRepository.java
> +    void deleteByProduct(Product target);
이 메서드에 대한 repository 테스트도 만드는 게 어떨까요?

2022-10-04 11:11 UTC, Youngyoon-1 approved these changes
고생하셨습니다!!

2022-10-04 11:11 UTC, Youngyoon-1 commented on backend/src/test/java/com/woowacourse/f12/presentation/product/ProductControllerTest.java
> +        final String authorizationHeader = "Bearer token";
여기도 final 있어요

2022-10-05 02:01 UTC, yh20studio approved these changes
좋은 리뷰 반영입니다~

2022-10-05 02:03 UTC, Ohzzi approved these changes

2022-10-05 02:08 UTC, merged