[Feature/BE] 인기 제품 조회 API 구현
woowacourse-teams/2022-f12 pull request #738
Opened 2022-10-12 05:17 UTC by Youngyoon-1

# issue: closes #731 

# 작업 내용
인기 제품 조회 API 구현

2022-10-12 09:42 UTC, Ohzzi requested changes
칙촉 고생 많았습니다!
비즈니스 조건이 바뀌게 되었으니 한 번 엎어야겠네요
RC 해두겠으니 수정 이후 다시 한 번 확인하도록 하겠습니다!

2022-10-12 09:42 UTC, Ohzzi commented on backend/src/test/java/com/woowacourse/f12/application/product/PopularProductStrategyTest.java
> +    @MethodSource("definitionProvider")
불필요하게 많은 테스트 같아요. 굳이 가능한 조건은 어마어마하게 많은데 어중간하게 여러 개의 조건을 테스트할 필요가 있을까요?

2022-10-13 01:57 UTC, Youngyoon-1 commented on backend/src/main/java/com/woowacourse/f12/domain/product/ProductRepositoryCustomImpl.java
> +    }
넵!! QueryDSL 대신에 ProductRepository 에서 쿼리 메서드 기능을 적용했습니다!!

2022-10-13 08:22 UTC, Youngyoon-1 commented on backend/src/main/java/com/woowacourse/f12/application/product/ProductService.java
> +        return popularProductStrategy.getResult(productRepository::findByReviewCountAndRatingGreaterThanEqual);
먼저 ProductService 에서 인기 제품 기준(rivewCount, rating)을 직접 알고 있는게 어색하다고 느껴져서 분리했습니다.
이 과정에서 `popularProductStrategy 에게 인기 제품 기준값을 물어본다 -> DB 조회 ->  popularProductStrategy 에게 조회 결과를 넘겨서 전략을 실행시킨다` 이런 흐름으로 로직이 구성됐습니다. 차라리 인기 제품 기준 값을 알고있는 popularProductStrategy에게 콜백 전달해서 한 번에 처리하도록 하기 위함입니다!

2022-10-13 08:37 UTC, Youngyoon-1 commented on backend/src/test/java/com/woowacourse/f12/application/product/PopularProductStrategyTest.java
> +    @MethodSource("definitionProvider")
넵 해당 부분은 리팩토링했습니다!!

2022-10-13 08:42 UTC, Youngyoon-1 commented on backend/src/main/java/com/woowacourse/f12/presentation/product/ProductController.java
> +    }
캐싱을 염두한건 아니에요. 처음에는 sql에서 rand() 을 사용해서 데이터를 조회했지만 쿼리 속도의 이점을 얻기 위해서 제품을 다 긁어와서 랜덤을 적용해줬습니다.

2022-10-13 11:25 UTC, yangdongjue5510 approved these changes
고생하셨습니다 칙촉!
꽤 어려운 문제였는데 잘 풀어가셨네요!

2022-10-13 11:25 UTC, yangdongjue5510 commented on backend/src/test/java/com/woowacourse/f12/presentation/product/ProductControllerTest.java
> +                .build();
Product를 생성하는 픽스처 메서드를 만들어서 활용해보면 어떨까요??

2022-10-13 15:15 UTC, yh20studio requested changes
칙촉 어려운 구현 하느라 고생하셨습니다 
몇가지 확인해주셨으면 하는 부분이 있어서 RC 남기겠습니다.

2022-10-13 15:15 UTC, yh20studio commented on backend/src/test/java/com/woowacourse/f12/acceptance/ProductAcceptanceTest.java
> +        // given
해당 테스트는 yml 파일에 value 값을 바꿈에 따라서 테스트가 통과할 수도, 실패할 수도 있을 거 같은데 상관없이 해결할 수 있는 방법이 있을까요?

2022-10-13 15:15 UTC, yh20studio commented on backend/src/test/java/com/woowacourse/f12/application/product/ProductServiceTest.java
> +
Repository 또한 동작할텐데 이건 테스트에 안 넣은 이유가 있을까요?

2022-10-13 15:15 UTC, yh20studio commented on backend/src/main/java/com/woowacourse/f12/presentation/product/ProductController.java
> +    }
size가 파라미터로 들어오게 되는데, 만약에 10000 와 같이 매우 큰수가 들어올 경우에는 물론 DB에 size라는 숫자가 직접적으로 들어가는 것은 아니지만 그만큼의 많은 숫자가 return될 경우가 있기 때문에 제한을 두어서 안정성을 두어야한다고 생각합니다. 
또한 -1과 같이 0보다 작은 숫자가 들어오는 경우에는 `stream.limit()`의 경우에 exception이 터지게 되는데 테스트를 해보니 50000 에러코드를 리턴하더군요. 이 부분에도 제한을 두어야한다고 생각하고 이에 맞는 테스트도 작성 됐으면 좋겠습니다

2022-10-13 15:38 UTC, yh20studio commented on backend/src/main/java/com/woowacourse/f12/domain/product/ProductRepository.java
> +    List<Product> findByReviewCountAndRatingGreaterThanEqual(int reviewCount, double rating);
<img width="447" alt="스크린샷 2022-10-14 오전 12 36 45" src="https://user-images.githubusercontent.com/78459713/195641897-d363b9fd-a9b1-47d0-98f0-121b2bb7cf4c.png">
 
해당 메서드에서 나가는 쿼리인데, ReviewCount에 경우는 equal 로 where 조건이 걸리고 있는데 의도한게 맞을까요?

2022-10-13 17:36 UTC, hamcheeseburger approved these changes
칙촉 수고하셨습니다~!! 코드에서 많이 고민하신게 느껴져요~!!!
티키가 남긴 리뷰만 반영하면 크게 문제될 것 없는 것 같아서 approve하겠습니다~~!!

2022-10-13 17:36 UTC, hamcheeseburger commented on backend/src/test/java/com/woowacourse/f12/domain/product/ProductRepositoryTest.java
> +
둘 다 결과값으로 반환되는 케이스 말고, 1개만 반환되는 케이스로 테스트해보는 것은 어떨까요? 제대로 조건문이 동작하는지 보려면 말씀드린 방법이 확실할 것 같아서요!

2022-10-14 02:21 UTC, Youngyoon-1 commented on backend/src/test/java/com/woowacourse/f12/presentation/product/ProductControllerTest.java
> +                .build();
넵 픽스처로 만들어 볼께용

2022-10-14 03:16 UTC, Youngyoon-1 commented on backend/src/test/java/com/woowacourse/f12/acceptance/ProductAcceptanceTest.java
> +        // given
테스트 환경에서는 별도의 yml 파일에 값들을 설정해줬기 때문에 괜찮을것 같아요!

2022-10-15 04:49 UTC, Youngyoon-1 commented on backend/src/test/java/com/woowacourse/f12/application/product/ProductServiceTest.java
> +
create 메서드 내부에서 매번 새로운 함수형 인터페이스 구현체를 만들어 파라미터로 넘겨주고 있기 때문에 따로 mocking 할 수 없었습니다.  
하지만 서비스에서는 popularProductsCreator 의 create 호출만을 검증해도 무방한것 같습니다! 
실제 동작 테스트는 PopularProductsCreatorTest 에서 이미 검증하고 있습니다!!

2022-10-15 05:29 UTC, Youngyoon-1 commented on backend/src/main/java/com/woowacourse/f12/presentation/product/ProductController.java
> +    }
넵 최소값과 최대값을 지정해서 유효성 검증 로직을 PopularProductsCreator 에 추가했습니다!

2022-10-15 05:58 UTC, Youngyoon-1 commented on backend/src/main/java/com/woowacourse/f12/domain/product/ProductRepository.java
> +    List<Product> findByReviewCountAndRatingGreaterThanEqual(int reviewCount, double rating);
헉.. 로그 확인을 미처 못했네요. 꼼꼼한 리뷰 감사합니다!!

2022-10-15 05:58 UTC, Youngyoon-1 commented on backend/src/test/java/com/woowacourse/f12/application/product/PopularProductsCreatorTest.java
> +    void testMethodNameHere() {
넵 피드백 반영하겠습니다!

2022-10-15 06:01 UTC, Youngyoon-1 commented on backend/src/test/java/com/woowacourse/f12/domain/product/ProductRepositoryTest.java
> +
넵!! 피드백 감사합니다! 반영했습니다!

2022-10-15 15:01 UTC, yangdongjue5510 approved these changes
확인했습니다 고생하셨어요!

2022-10-16 11:53 UTC, Ohzzi approved these changes
수고하셨습니다 QA 과정에서 문제가 생기면 그부분만 수정하고 이만 머지하기로 합시다!

2022-10-16 12:13 UTC, yh20studio approved these changes
칙촉 리뷰 반영하느라 고생많으셨습니다! 이만 approve 하겠습니다

2022-10-16 12:30 UTC, merged