[Feature/BE] 인메모리 저장소 대신 DB에 저장하도록 변경
woowacourse-teams/2022-f12 pull request #747
Opened 2022-10-13 01:03 UTC by yangdongjue5510

# issue: closes #734 

# 작업 내용
- JdbcTemplate를 사용해서 인메모리 대신 DB에 저장할 수 있도록 수정
- 다만 JPA Entity가 아니라서 ddl-auto로 테스트 때 스키마가 생성되지 않음 -> SQL 파일을 만들어서 인수테스트에서 사용

2022-10-13 03:56 UTC, Ohzzi requested changes
클레이 수고하셨습니다~!
수정해야 할 부분들이 몇 군데 있어서 RC 드릴게요!

2022-10-13 03:56 UTC, Ohzzi commented on backend/src/test/java/com/woowacourse/f12/application/auth/token/RefreshTokenRepositoryImplTest.java
> +        final RefreshToken actual = refreshTokenRepositoryImpl.findToken(tokenValue)
```suggestion
        RefreshToken actual = refreshTokenRepositoryImpl.findToken(tokenValue)
```

2022-10-13 03:56 UTC, Ohzzi commented on backend/src/test/resources/refreshTokenDDL.sql
> +    expired_at datetime not null,
왜 timestamp 대신 datetime을 사용하셨나요?

2022-10-13 03:56 UTC, Ohzzi commented on backend/src/test/java/com/woowacourse/f12/application/auth/token/RefreshTokenRepositoryImplTest.java
> +        assertThat(refreshTokenRepositoryImpl.findToken(tokenValue)).isEqualTo(Optional.empty());
assertThat에 Optional에 대해 테스트하는 메서드가 있습니다. assertThat 안에 Optional 값을 넣으면 OptionalAssert로 테스트하게되니 그냥 isEmpty() 사용해도 될 것 같아요

2022-10-13 03:56 UTC, Ohzzi commented on backend/src/main/java/com/woowacourse/f12/application/auth/token/RefreshTokenRepositoryImpl.java
> +            .expiredAt(rs.getTimestamp("expired_at").toLocalDateTime())
DB 타입 선언은 datetime 해놓고 getTimestamp...? 👀

2022-10-13 06:22 UTC, yangdongjue5510 commented on backend/src/test/resources/refreshTokenDDL.sql
> +    expired_at datetime not null,
timestamp를 사용하는게 맞습니다. 
timestamp를 사용하도록 수정하겠습니다!
다만 timestamp는 최대 2038-01-19 03:14:07까지만 지원한다고 하니 먼 미래에는 변경해야될 일이 있을 수도 있겠네요.

2022-10-13 06:23 UTC, yangdongjue5510 commented on backend/src/test/java/com/woowacourse/f12/application/auth/token/RefreshTokenRepositoryImplTest.java
> +        final RefreshToken actual = refreshTokenRepositoryImpl.findToken(tokenValue)
반영하겠습니다.

2022-10-13 06:25 UTC, yangdongjue5510 commented on backend/src/test/java/com/woowacourse/f12/application/auth/token/RefreshTokenRepositoryImplTest.java
> +        assertThat(refreshTokenRepositoryImpl.findToken(tokenValue)).isEqualTo(Optional.empty());
반영하겠습니다.

2022-10-13 06:27 UTC, yangdongjue5510 commented on backend/src/main/java/com/woowacourse/f12/application/auth/token/RefreshTokenRepositoryImpl.java
> +            .expiredAt(rs.getTimestamp("expired_at").toLocalDateTime())
refreshTokenDDL파일을 timestamp로 수정하겠습니다.

2022-10-13 06:47 UTC, yangdongjue5510 commented on backend/src/main/java/com/woowacourse/f12/application/auth/token/RefreshTokenRepositoryImpl.java
> +                refreshToken.getExpiredAt(), refreshToken.getMemberId());
NamedParameterJdbcTemplate를 활용해서 메서드 길이를 줄여보도록 하겠습니다.

2022-10-13 08:35 UTC, yangdongjue5510 commented on backend/src/main/java/com/woowacourse/f12/application/auth/token/RefreshTokenRepositoryImpl.java
> +        }
Optional을 반환하지 않고 대신 RefreshToken을 반한하도록 하겠습니다.
다만 예외 처리는 RefreshTokenRepository에서 하도록 수정했습니다.

2022-10-13 12:56 UTC, Youngyoon-1 approved these changes
금방 구현해주셨군요!! 역시 클레이~ 고생하셨습니당

2022-10-13 12:56 UTC, Youngyoon-1 commented on backend/src/main/java/com/woowacourse/f12/application/auth/token/RefreshTokenRepositoryImpl.java
> +            throw new IllegalArgumentException();
커스텀 예외를 사용하는건 어떨까요?! 👀

2022-10-13 12:56 UTC, Youngyoon-1 commented on backend/src/main/java/com/woowacourse/f12/application/auth/token/RefreshTokenRepositoryImpl.java
> +    private void validateAffectedRowCountIsOne(final int update) {
메서드 호출 순서대로 위치시키는건 어떨까요?

2022-10-13 12:56 UTC, Youngyoon-1 commented on backend/src/test/java/com/woowacourse/f12/application/auth/token/RefreshTokenRepositoryImplTest.java
> +
여기 빈 줄이 있네요 ㅎㅎ

2022-10-13 12:56 UTC, Youngyoon-1 commented on backend/src/test/java/com/woowacourse/f12/application/auth/token/RefreshTokenRepositoryImplTest.java
> +                .build();
모든 테스트에서 사용되는 값은 따로 필드로 빼주는건 어떨까요?

2022-10-13 12:56 UTC, Youngyoon-1 commented on backend/src/test/java/com/woowacourse/f12/presentation/auth/AuthControllerTest.java
> +    void 서버에_중복되어_저장된_리프레시_토큰으로_액세서_토큰을_발급하면_예외_발생() throws Exception {
액세서서갈비~

2022-10-13 15:56 UTC, yh20studio requested changes
클레이 고생하셨습니다~ 몇가지 확인할 부분이 있어서 RC 남겼습니다!
코멘트 확인 부탁드리겠습니다

2022-10-13 15:56 UTC, yh20studio commented on backend/src/main/java/com/woowacourse/f12/application/auth/token/RefreshTokenRepositoryImpl.java
> +        }
👍

2022-10-13 15:56 UTC, yh20studio commented on backend/src/main/java/com/woowacourse/f12/application/auth/token/RefreshTokenRepositoryImpl.java
> +                    .queryForObject(sql, rowMapper, savedTokenValue);
NamedParameterJdbcTemplate을 쓰기에 이왕이면 SqlParameterSource으로 값을 넘겨주고, `?` 대신 `:`를 사용하는 건 어떨까요?

2022-10-13 15:56 UTC, yh20studio commented on backend/src/main/java/com/woowacourse/f12/application/auth/token/RefreshTokenRepositoryImpl.java
> +                .update(sql, savedTokenValue);
여기도 마찬가지 입니다. NamedParameterJdbcTemplate을 쓰기에 이왕이면 SqlParameterSource으로 값을 넘겨주고, ? 대신 :를 사용하는 건 어떨까요?

2022-10-13 15:56 UTC, yh20studio commented on backend/src/test/java/com/woowacourse/f12/application/auth/token/RefreshTokenRepositoryImplTest.java
> +    }
```suggestion
    private RefreshTokenRepositoryImpl refreshTokenRepositoryImpl;

    @Autowired
    RefreshTokenRepositoryImplTest(final NamedParameterJdbcTemplate namedParameterJdbcTemplate) {
        this.refreshTokenRepositoryImpl = new RefreshTokenRepositoryImpl(namedParameterJdbcTemplate);
    }
```
BeforeEach로 매번 생성하는 것보다 이렇게 처리하는 건 어떨까요?

2022-10-13 15:56 UTC, yh20studio commented on backend/src/test/java/com/woowacourse/f12/application/auth/token/RefreshTokenRepositoryImplTest.java
> +class RefreshTokenRepositoryImplTest {
해당 테스트와 실제 운영환경에서도 jpa hibernate를 사용하지 않기에 로그가 찍히지 않는 것으로 보입니다. 찍기 위해서는 `'com.googlecode.log4jdbc:log4jdbc:` 다음과 같은 의존성을 추가해야한다고 하는데 어떻게 생각하시나요?

2022-10-13 15:56 UTC, yh20studio commented on backend/src/test/java/com/woowacourse/f12/application/auth/token/RefreshTokenRepositoryImplTest.java
> +                .isEqualTo(refreshToken);
```suggestion
        assertThat(actual).isEqualTo(refreshToken);
```
이렇게 검증해도 무방하다고 봅니다

2022-10-14 01:46 UTC, yangdongjue5510 commented on backend/src/main/java/com/woowacourse/f12/application/auth/token/RefreshTokenRepositoryImpl.java
> +            throw new IllegalArgumentException();
TooManyRefreshTokenAffectedException이라는 커스텀 예외를 만들어주도록 하겠습니다.

2022-10-14 01:47 UTC, yangdongjue5510 commented on backend/src/main/java/com/woowacourse/f12/application/auth/token/RefreshTokenRepositoryImpl.java
> +    private void validateAffectedRowCountIsOne(final int update) {
validateAffectedRowCountIsOne 메서드가 최초 호출된 메서드 다음에 오도록 수정하겠습니다.

2022-10-14 02:01 UTC, yangdongjue5510 commented on backend/src/test/java/com/woowacourse/f12/application/auth/token/RefreshTokenRepositoryImplTest.java
> +
제거할게요!

2022-10-14 02:15 UTC, yangdongjue5510 commented on backend/src/test/java/com/woowacourse/f12/application/auth/token/RefreshTokenRepositoryImplTest.java
> +                .build();
필드로 빼도록 할게요!!

2022-10-14 02:22 UTC, yangdongjue5510 commented on backend/src/test/java/com/woowacourse/f12/application/auth/token/RefreshTokenRepositoryImplTest.java
> +    }
반영하도록 하겠습니다.

2022-10-14 02:33 UTC, yangdongjue5510 commented on backend/src/main/java/com/woowacourse/f12/application/auth/token/RefreshTokenRepositoryImpl.java
> +                    .queryForObject(sql, rowMapper, savedTokenValue);
반영하겠습니다.

2022-10-14 02:34 UTC, yangdongjue5510 commented on backend/src/main/java/com/woowacourse/f12/application/auth/token/RefreshTokenRepositoryImpl.java
> +                .update(sql, savedTokenValue);
반영했습니다.

2022-10-14 02:34 UTC, yangdongjue5510 commented on backend/src/test/java/com/woowacourse/f12/presentation/auth/AuthControllerTest.java
> +    void 서버에_중복되어_저장된_리프레시_토큰으로_액세서_토큰을_발급하면_예외_발생() throws Exception {
액세스_토큰 이라고 수정하겠습니다.

2022-10-14 03:17 UTC, yangdongjue5510 commented on backend/src/test/java/com/woowacourse/f12/application/auth/token/RefreshTokenRepositoryImplTest.java
> +class RefreshTokenRepositoryImplTest {
따로 이슈를 만들어서 진행하도록 하겠습니다.

2022-10-14 04:18 UTC, hamcheeseburger approved these changes
클레이 수고하셨습니다~~! 다른분들이 리뷰 잘해주셔서 딱히 드릴게 없네요!
어프루브 하겠습니다~!

2022-10-14 04:18 UTC, hamcheeseburger commented on backend/src/main/java/com/woowacourse/f12/application/auth/token/RefreshTokenRepositoryImpl.java
> +        if (update != 1) {
매직넘버 제거하는 것은 어떨까요~! 그리고 변수명 update보다 더 좋은 네이밍이 있을 것 같아요!

2022-10-14 05:16 UTC, yangdongjue5510 commented on backend/src/main/java/com/woowacourse/f12/application/auth/token/RefreshTokenRepository.java
> +   RefreshToken findToken(String savedTokenValue);
수정하겠습니다.

2022-10-14 05:18 UTC, yangdongjue5510 commented on backend/src/main/java/com/woowacourse/f12/application/auth/token/RefreshTokenRepositoryImpl.java
> +        if (update != 1) {
매개변수 update는 affectedCount로 수정하겠습니다!
매직넘버는 상수로 따로 뽑도록 하겠습니다!

2022-10-14 06:28 UTC, yh20studio commented on backend/src/test/java/com/woowacourse/f12/application/auth/token/RefreshTokenRepositoryImplTest.java
> +class RefreshTokenRepositoryImplTest {
감사합니다 클레이 최고

2022-10-14 06:29 UTC, yh20studio approved these changes
고생하셨습니다 리뷰 잘 적용하신 거보고 어프루브 합니다

2022-10-14 07:18 UTC, Ohzzi approved these changes
굿!

2022-10-14 07:46 UTC, merged