[Feature/BE] DB replication을 적용한다
woowacourse-teams/2022-f12 pull request #785
Opened 2022-10-17 08:20 UTC by hamcheeseburger

# 작업 내용
- main, performance, release에 대한 submodule을 수정
- DataSource 이중화 및 Transaction readOnly 여부에 따른 DataSource 선택 로직 추가
- Test 코드 상에서는 DB 이원화를 사용하지 않음. 다만 DB 이원화의 동작을 테스트하는 파일 존재.

2022-10-18 04:37 UTC, yangdongjue5510 requested changes
티키, 코린 고생하셨습니다!!!
코멘트 확인부탁드려요!

2022-10-18 04:37 UTC, yangdongjue5510 commented on backend/src/main/java/com/woowacourse/f12/config/DatasourceConfig.java
> +        bean.setJpaPropertyMap(properties);
`bean.setJpaPropertyMap(Map.of("hibernate.format_sql:, formatSqlValue));` 해보는 건 어떨까요?

2022-10-18 04:37 UTC, yangdongjue5510 commented on backend/src/main/java/com/woowacourse/f12/config/DatasourceConfig.java
> +@Profile({"main", "release", "performance"})
테스트에서 사용되지 않도록 main, release, performance 프로파일에만 작동하도록 설정하셨군요!!!👍

2022-10-18 04:37 UTC, yangdongjue5510 commented on backend/src/test/java/com/woowacourse/f12/config/TestDataSourceConfig.java
> +                .url("jdbc:h2:mem:master;MODE=MySQL;")
datasource의 url을 public한 상수로 관리해서 테스트 검증할 때 해당 상수값을 import해서 사용하면 어떨까요?

2022-10-18 04:37 UTC, yangdongjue5510 commented on backend/src/test/java/com/woowacourse/f12/config/DatasourceConfigTest.java
> +        assertThat(url).isEqualTo("jdbc:h2:mem:master");
TestDataSourceConfig에서 URL을 Public한 상수로 관리하고 여기서 import 해서 사용하면 어떨까요

2022-10-18 04:37 UTC, yangdongjue5510 commented on backend/src/test/java/com/woowacourse/f12/config/TestDataSourceConfig.java
> +        return new JpaTransactionManager(entityManagerFactoryBean);
JPA가 아닌 경우에도 트랜잭션 매니저가 잘 작동하는지 확인 부탁드립니다!

2022-10-18 05:36 UTC, yh20studio commented on backend/src/test/java/com/woowacourse/f12/config/TestDataSourceConfig.java
> +        return new JpaTransactionManager(entityManagerFactoryBean);
JDBC 도 해당 트랜잭션 매니저로 잘 작동합니다.
확인해보니 JPA가 없다면 JdbcTransactionManager를 생성하지만, JPA 환경에서는 JpaTransactionManager를 생성하게 됩니다.
사진은 JpaTransactionManager의 주석입니다.
<img width="672" alt="스크린샷 2022-10-18 오후 2 33 42" src="https://user-images.githubusercontent.com/78459713/196344003-12ccba0c-a044-4536-b17b-d0785c86d9c6.png">

2022-10-18 07:52 UTC, Youngyoon-1 approved these changes
와 고생 많으셨습니다!!

2022-10-18 12:56 UTC, hamcheeseburger commented on backend/src/main/java/com/woowacourse/f12/support/ReplicationRoutingDataSource.java
> +        final String transactionName = TransactionSynchronizationManager.getCurrentTransactionName();
<img width="1040" alt="스크린샷 2022-10-18 21 52 53" src="https://user-images.githubusercontent.com/61769743/196435010-87716876-f1f1-4f3b-8031-302dd0894cc8.png">

해당 트랜잭션이 적용된 메서드 이름을 반환합니다.!

2022-10-19 05:12 UTC, yh20studio commented on backend/src/test/java/com/woowacourse/f12/config/DatasourceConfigTest.java
> +        assertThat(url).isEqualTo("jdbc:h2:mem:master");
개인적으로는 test 검증 부분에서 상수를 사용하면 안된다고 생각합니다.

2022-10-19 05:13 UTC, yh20studio commented on backend/src/test/java/com/woowacourse/f12/config/TestDataSourceConfig.java
> +                .url("jdbc:h2:mem:master;MODE=MySQL;")
테스트 검증시에는 Mode=mysql이 없기 때문에 좀 더 복잡해질 수 있어서 Config 파일 내에서 상수로만 정의하고 사용하겠습니다

2022-10-19 05:14 UTC, yh20studio commented on backend/src/main/java/com/woowacourse/f12/config/DatasourceConfig.java
> +        bean.setJpaPropertyMap(properties);
반영했습니다

2022-10-19 05:16 UTC, yh20studio commented on backend/src/main/java/com/woowacourse/f12/support/ReplicationRoutingDataSource.java
> +        }
반영했습니다!

2022-10-19 05:16 UTC, yh20studio commented on backend/src/test/java/com/woowacourse/f12/config/DatasourceConfigTest.java
> +    TransactionTestService transactionTestService;
반영했습니다!

2022-10-19 05:16 UTC, yh20studio commented on backend/src/test/java/com/woowacourse/f12/config/TransactionTestService.java
> +    EntityManager entityManager;
반영했습니다!

2022-10-19 06:42 UTC, yangdongjue5510 approved these changes
변경사항 확인했습니다!
고생하셨습니다 티키 코린!

2022-10-19 06:42 UTC, yangdongjue5510 commented on backend/src/test/java/com/woowacourse/f12/config/TestDataSourceConfig.java
> +        return new JpaTransactionManager(entityManagerFactoryBean);
네 확인했습니다!!

2022-10-19 08:51 UTC, merged