[Bugfix/FE] intersection observer 오류 수정
woowacourse-teams/2022-f12 pull request #857
Opened 2022-10-26 07:12 UTC by uk960214

# issue: closes #856 

# 작업 내용
무한스크롤 오류 수정
- 첫 화면에서 두 페이지 (초기 + 그 다음)을 불러오면 발생
- intersection observer는 isIntersecting이 false에서 true로 변경될 때 콜백함수가 실행
- 위 엣지 케이스에서는 계속 화면에 intersecting이어서 그 다음 페이지를 불러오지 않음
- useEffect 훅을 사용해 children이 변경될 때 cleanup 콜백함수로 unobserve 한 뒤 다시 observe하도록 해서 화면에 존재하는 동안에는 새로운 데이터를 불러운 뒤 계속 콜백함수가 호출되도록 수정

```ts
useEffect(() => {
  if (!endRef.current) return;
  endOfContentObserver.observe(endRef.current);

  return () => {
    if (!endRef.current) return;
    endOfContentObserver.unobserve(endRef.current);
  };
}, [children]);
```

2022-10-26 08:09 UTC, jswith requested changes
고생하셨습니다! 확인 부탁드려요~

2022-10-26 08:09 UTC, jswith commented on frontend/src/index.tsx
> -}
테스트 끝나신 뒤에는 모킹 다시 켜주셔야 될 것 같아요~

2022-10-26 08:09 UTC, jswith commented on frontend/src/components/common/InfiniteScroll/InfiniteScroll.tsx
> +
```suggestion
  useEffect(() => {
    endOfContentObserver.observe(endRef.current);

    return () => {
      endOfContentObserver.unobserve(endRef.current);
    };
  }, [children]);

```

2022-10-26 08:09 UTC, jswith commented on frontend/src/components/common/InfiniteScroll/InfiniteScroll.tsx
> +
이렇게 작성하는 것과는 어떤 차이가 있나요?

2022-10-27 01:46 UTC, uk960214 commented on frontend/src/components/common/InfiniteScroll/InfiniteScroll.tsx
> +
endRef의 존재여부를 검사하지 않으면 발생하는 문제를 물어보시는 건가요?
그렇게 되면 endRef가 렌더링되지 않은 상황에서 endRef.current가 HTMLElement가 아니라서 observe할 수 없다는 오류가 발생합니다!
return하는 콜백함수에도 다시 써준 이유는 clean up이 이뤄지는 상황에서는 전체 useEffect 콜백함수가 실행되는 것이 아니라 return에 전달된 콜백함수만 실행되고 이 스코프에서는 endRef.current를 검증하지 않았기 때문에 endRef.current가 null 이라면 오류가 발생하더라구요!

2022-10-27 03:07 UTC, jswith commented on frontend/src/components/common/InfiniteScroll/InfiniteScroll.tsx
> +
endRef가 렌더링 되지 않는 상황이 infinite scroll의 children은 존재하지만, endRef로 선택한 요소가 존재하지 않는 경우라는 말씀이시죠? 그런 경우라면 체크해줄 필요가 있겠네요!

2022-10-27 03:09 UTC, jswith commented on frontend/src/components/common/InfiniteScroll/InfiniteScroll.tsx
> +
endRef가 렌더링 되지 않는 상황이 infinite scroll의 children과는 별개로, endRef로 선택한 요소가 존재하지 않는 경우라는 말씀이시죠? 그런 경우라면 체크해줄 필요가 있겠네요!

2022-10-27 03:14 UTC, jswith approved these changes
고생하셨습니다!

2022-10-27 05:52 UTC, merged