[FE] 스프린트 종료 전 리팩토링
woowacourse-teams/2022-f12 pull request #869
Opened 2022-11-10 04:45 UTC by uk960214

# issue: #868

# 작업 내용
- 불필요한 파일 제거: legacy 파일 (axiosInstance) 제거 -> 이미 axios 훅으로 대체 중
- babel과 ts-loader로 둘 다 컴파일 하도록 설정 (아직 babel의 core-js 폴리필을 ts-loader에서 제공하는 지 알 수 없음, 임시 조치)
- babel config에서 core-js 설정 변경 (빌드 결과물 크기 최적화, [자세한 내용](https://medium.com/@uk960214/babel%EC%9D%84-%EC%82%AC%EC%9A%A9%ED%95%B4%EB%8F%84-%EC%B5%9C%EC%8B%A0-js-%EB%AC%B8%EB%B2%95%EC%9D%84-%EC%82%AC%EC%9A%A9%ED%95%A0-%EC%88%98-%EC%97%86%EC%9D%84-%EB%95%8C-core-js-polyfill-13db50aa7cf5))
- webpack에 불필요한 설정 필드 제거 (prod에 entry 필드 불필요)
- mock 데이터 및 핸들러 파일 주제 별로 분리

2022-11-11 03:23 UTC, jswith requested changes
핸들러 깔끔하게 잘 분리하셨네요!
몇 가지 리뷰 남겼습니당

2022-11-11 03:23 UTC, jswith commented on frontend/babel.config.json
> +        "useBuiltIns": "usage",
👍🏻

2022-11-11 03:23 UTC, jswith commented on frontend/src/index.tsx
> -import 'core-js/stable';
stable을 import하는 것과 하지 않는 것의 차이는 무엇인가요?

2022-11-11 03:23 UTC, jswith commented on frontend/webpack.common.js
> +        use: ['babel-loader', 'ts-loader'],
> babel과 ts-loader로 둘 다 컴파일 하도록 설정 (아직 babel의 core-js 폴리필을 ts-loader에서 제공하는 지 알 수 없음, 임시 조치)

이 부분은 tsconfig의 lib 옵션을 활용하면 해결되지 않을까요?
lib에 es2022를 추가해주면 core-js 폴리필 없이도 tsconfig만으로도 해결할 수 있지 않을까 싶습니다.
아직 추측이긴 합니다 👀

https://www.typescriptlang.org/tsconfig#lib

2022-11-11 03:23 UTC, jswith commented on frontend/webpack.prod.js
> -  entry: './src/index.tsx',
common에서 이미 merge하고 있는 구문이 중복 작성되어 있어 삭제하신건가요?

2022-11-12 12:15 UTC, uk960214 commented on frontend/src/index.tsx
> -import 'core-js/stable';
usage 설정을 하고 import 하지 않으면 자동으로 현재 사용 중인 함수와 매서드에 대한 폴리필을 찾아 추가해줍니다! import 했을 때보다 안했을 때 번들 크기가 더 작더라구요!

2022-11-12 15:53 UTC, jswith approved these changes
답변 확인했습니다 머지할게요!

2022-11-12 15:53 UTC, merged